
---
apiVersion: v1
kind: Service
metadata:
  name: {{appName}}-svc
  labels:
    app: {{appName}}
  namespace: {{namespace}}
spec:
  type: NodePort
  ports:
    - port: {{port}}
      name: port3
      protocol: TCP
      targetPort: {{targetPort}}
      nodePort: {{nodePort}}
  selector:
    app: {{appName}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{appName}}-deployment
  labels:
    app: {{appName}}
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{appName}}
  template:
    metadata:
      labels:
        app: {{appName}}
    spec:
      containers:
        - name: {{appName}}-container
          image: {{imageName}}:{{version}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{containerPort}}
      imagePullSecrets:
        - name: {{imagePullSecrets}}
